udev
changed udev ver

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -270,9 +270,9 @@ SHELL=${CONFIG_SHELL-/bin/sh}
 # Identity of this package.
 PACKAGE_NAME='midisport-firmware'
 PACKAGE_TARNAME='midisport-firmware'
-PACKAGE_VERSION='1.2'
-PACKAGE_STRING='midisport-firmware 1.2'
-PACKAGE_BUGREPORT='usb-midi-fw-user@lists.sourceforge.net'
+PACKAGE_VERSION='1.3'
+PACKAGE_STRING='midisport-firmware 1.3'
+PACKAGE_BUGREPORT='https://github.com/oeai/m-audio-usb-midi-fw/issues'
 
 ac_unique_file="MidiSportLoader.ihx"
 ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot FXLOAD UDEV_RULES_DIR LIBOBJS LTLIBOBJS'
@@ -724,7 +724,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the A/UX 3.1 sh.
   cat <<_ACEOF
-\`configure' configures midisport-firmware 1.2 to adapt to many kinds of systems.
+\`configure' configures midisport-firmware 1.3 to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -786,7 +786,7 @@ fi
 
 if test -n "$ac_init_help"; then
   case $ac_init_help in
-     short | recursive ) echo "Configuration of midisport-firmware 1.2:";;
+     short | recursive ) echo "Configuration of midisport-firmware 1.3:";;
    esac
   cat <<\_ACEOF
 
@@ -1746,9 +1746,9 @@ else
 echo "${ECHO_T}none" >&6
   udev_ver="0"
 fi
-if test "$udev_ver" -lt 057; then
-  { { echo "$as_me:$LINENO: error: udev version 057 or later is required" >&5
-echo "$as_me: error: udev version 057 or later is required" >&2;}
+if test "$udev_ver" -lt 128; then
+  { { echo "$as_me:$LINENO: error: udev version 128 or later is required" >&5
+echo "$as_me: error: udev version 128 or later is required" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -2257,7 +2257,7 @@ _ACEOF
 
 cat >>$CONFIG_STATUS <<_ACEOF
 ac_cs_version="\\
-midisport-firmware config.status 1.2
+midisport-firmware config.status 1.3
 configured by $0, generated by GNU Autoconf 2.59,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
